package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
)

// Sentence is one fill-in-the-blank sentence for an item (ENCRE_04 §6's
// sentences table), generated by [github.com/oioio-space/encre/server/gen]
// or typed by the parent directly — [Sentence] carries no field
// distinguishing the two, because once saved they are reviewed and played
// identically; only Approved decides whether a run's deck may draw it.
type Sentence struct {
	ID     string
	ItemID string
	// Text is the sentence, gap included ("Le ___ dort sur le lit.").
	Text string
	// TargetForm is the target word as it is actually written in Text's
	// gap — accorded, when the item's Couleur asks for that.
	TargetForm string
	// AudioPath is where the parent's or Piper's recording lives, relative
	// to the media root, or "" before one is attached.
	AudioPath string
	// Approved says whether the parent has accepted this sentence
	// (ENCRE_04 §7, "le parent valide chaque phrase d'un tap").
	Approved bool
}

// SaveSentence inserts s, or replaces it in place if s.ID already exists.
// It returns an error if s.ItemID names no item.
func (st *Store) SaveSentence(ctx context.Context, s *Sentence) error {
	_, err := st.db.ExecContext(ctx, `
		INSERT INTO sentences (id, item_id, text, target_form, audio_path, approved)
		VALUES (?, ?, ?, ?, ?, ?)
		ON CONFLICT(id) DO UPDATE SET
			item_id = excluded.item_id, text = excluded.text, target_form = excluded.target_form,
			audio_path = excluded.audio_path, approved = excluded.approved`,
		s.ID, s.ItemID, s.Text, s.TargetForm, s.AudioPath, s.Approved)
	if err != nil {
		return fmt.Errorf("saving sentence: %w", err)
	}
	return nil
}

// SentenceByID returns the sentence with the given ID, or [ErrNotFound] if
// none exists.
func (st *Store) SentenceByID(ctx context.Context, id string) (*Sentence, error) {
	row := st.db.QueryRowContext(ctx, sentenceSelect+`WHERE id = ?`, id)
	s, err := scanSentence(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	return s, err
}

// SentencesOfItem returns every sentence belonging to the given item, in no
// particular order.
func (st *Store) SentencesOfItem(ctx context.Context, itemID string) ([]*Sentence, error) {
	rows, err := st.db.QueryContext(ctx, sentenceSelect+`WHERE item_id = ?`, itemID)
	if err != nil {
		return nil, fmt.Errorf("querying sentences: %w", err)
	}
	defer func() { _ = rows.Close() }()

	var sentences []*Sentence
	for rows.Next() {
		s, err := scanSentence(rows)
		if err != nil {
			return nil, err
		}
		sentences = append(sentences, s)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating sentences: %w", err)
	}
	return sentences, nil
}

// ApproveSentence marks the sentence approved. It returns [ErrNotFound] if
// no sentence with that ID exists.
func (st *Store) ApproveSentence(ctx context.Context, id string) error {
	result, err := st.db.ExecContext(ctx, `UPDATE sentences SET approved = 1 WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("approving sentence: %w", err)
	}
	return requireRowAffected(result, "approving sentence")
}

// DeleteSentence removes the sentence with the given ID. It returns
// [ErrNotFound] if none exists.
func (st *Store) DeleteSentence(ctx context.Context, id string) error {
	result, err := st.db.ExecContext(ctx, `DELETE FROM sentences WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("deleting sentence: %w", err)
	}
	return requireRowAffected(result, "deleting sentence")
}

const sentenceSelect = `SELECT id, item_id, text, target_form, audio_path, approved FROM sentences `

// sentenceScanner is what [sql.Row] and [sql.Rows] share of the Scan
// method, letting scanSentence serve both a single-row and a multi-row
// query.
type sentenceScanner interface {
	Scan(dest ...any) error
}

func scanSentence(row sentenceScanner) (*Sentence, error) {
	var s Sentence
	err := row.Scan(&s.ID, &s.ItemID, &s.Text, &s.TargetForm, &s.AudioPath, &s.Approved)
	if err != nil {
		return nil, fmt.Errorf("scanning sentence: %w", err)
	}
	return &s, nil
}
